[package]
name = "source"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libloading = "0.6"
actix-web = "4"
env_logger = "0.10.0"
log = { version = "0.4.0-rc.1" }
reqwest = { version = "0.11", features = ["json"] }